name: Test PR

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Copy README to python package directory
      run: |
        cp README.md src/python/
    
    - name: Install dependencies
      run: |
        cd src/python
        uv sync
    
    - name: Run test_messages.py
      env:
        LETTA_API_KEY: ${{ secrets.LETTA_API_KEY }}
      run: |
        cd src/python
        uv run pytest tests/test_messages.py -v